name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
  deployToTest:
    runs-on: ubuntu-latest
    environment: Test
    
    steps:
      - name: GatedWait
        run: echo Hello
