name: 3 Ringbased
on:
  workflow_dispatch:


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
  Stage:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: Ring0
      url: http://user-internal.com
    steps:
      - run: echo "Push things to target...."
  Canaries-20:
    runs-on: ubuntu-latest
    needs: Stage
    environment: 
      name: Ring1
      url: http://user-20.com
    steps:
      - run: echo "Push things to target...."
  EarlyAdopter-50:
    runs-on: ubuntu-latest
    needs: Canaries-20
    environment: 
      name: Ring2
      url: http://user-50.com
    steps:
      - run: echo "Push things to target...."
  Users-100:
    runs-on: ubuntu-latest
    needs: EarlyAdopter-50
    environment: 
      name: Ring3
      url: http://user-100.com
    steps:
      - run: echo "Push things to target...."