name: 3 Ringbased
on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
  Ring0:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Push things to target...."
  Ring1:
    runs-on: ubuntu-latest
    needs: Ring0
    environment: Ring1
    steps:
      - run: echo "Push things to target...."
  Ring2:
    runs-on: ubuntu-latest
    needs: Ring1
    environment: Ring1
    steps:
      - run: echo "Push things to target...."
  Ring3:
    runs-on: ubuntu-latest
    needs: Ring2
    environment: Ring1
    steps:
      - run: echo "Push things to target...."