name: 3 Ringbased
on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
  Test_Stage:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      - name: Ring0
      - url: first 5% internal user
    steps:
      - run: echo "Push things to target...."
  Canaries:
    runs-on: ubuntu-latest
    needs: Test_Stage
    environment: Ring1
    steps:
      - run: echo "Push things to target...."
  EarlyAdopter:
    runs-on: ubuntu-latest
    needs: Canaries
    environment: Ring2
    steps:
      - run: echo "Push things to target...."
  Users:
    runs-on: ubuntu-latest
    needs: EarlyAdopter
    environment: Ring3
    steps:
      - run: echo "Push things to target...."