name: SimpleWf

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
  Prod-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Push things to target...."
